// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ggczjdgtzkfapkfjwrid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnY3pqZGd0emtmYXBrZmp3cmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzg3NTQsImV4cCI6MjA2NTY1NDc1NH0.gGFp50pQyoSbM8oMfC-dXG8lstFPu0tFXlS6QqarNj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);